version: '3.8'
services:
  api1:
    build:
      context: .
      dockerfile: ./Api1/Dockerfile
    ports: 
      - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    hostname: api1
    networks:
      - selecao

  api2:
    build:
      context: .
      dockerfile: ./Api2/Dockerfile
    ports: 
      - "8081:8081"
    environment:
      Api1Uri: http://api1:8080
      ASPNETCORE_ENVIRONMENT: Development
    networks:
      - selecao
    hostname: api2
  
  test:
    image: mcr.microsoft.com/dotnet/sdk:5.0
    environment:
      Api1Uri: http://api1:8080
      Api2Uri: http://api2:8081
    volumes:
      - .:/src
      - ./tests:/tests
    working_dir: /src 
    command:
      [
        "dotnet",
        "test",
        "../tests/tests.csproj"
      ]
    networks:
      - selecao
    depends_on:
      - api1
      - api2
    profiles:
      - donotstart

networks:
  selecao:
    driver: bridge